### ISSUE TITLE
Remove Try/Catch in test_connectivity

### ISSUE THREAD

**Issue by zdc217** [techservicesillinois/clearpass-api#21]
https://github.com/techservicesillinois/clearpass-api/blob/0239dd8f765ce2224325fa085d8a0bf30f3ab0b6/src/clearpass/client.py#L86-L91

Lines 90 and 91 are not allowing the exception to bubble up to the SOAR log so we don't know what is happening when the `test_connectivity` function fails in the SOAR Clearpass app. Removing those lines should give us a clearer error message.

**Comment by edthedev** [comment]
Main thing is not to catch `Exception` here.

**Comment by edthedev** [comment]
Let's try to catch usuals, 

- 403 - fix your password
- time-out - fix your networking
- 404 - fix your URL config
- 500 - upstream is broken, talk to them

**Comment by edthedev** [comment]
Note that, we also need to refactor the unit tests around test_connectivity.

**Comment by edthedev** [comment]
Blocks clearpass app release.

**Comment by tzturner** [comment]
Note that `_get_access_token()` is failing on SOAR. We should test the `clearpass-api` locally on `csoctools02-dev` to ensure the function works as expected.

**Comment by edthedev** [comment]
Latest output from `test_connectivity` in SOAR Test Clearpass app.

```sh
============ Environment Debug ============

  Interpreter: Python 3.9.9

  Installed dependencies:

	clearpass @ file:///opt/phantom/apps/app_install_33rye736/app/wheels/clearpass-0.1.dev13-py3-none-any.whl#sha256=15620744502f2149b73d6f94987ca31fb019e2cfdfd71ceda7cf30cae8cfa6a5

	phantom-toolbox @ file:///opt/phantom/apps/app_install_33rye736/app/wheels/phantom_toolbox-0.1.dev29-py3-none-any.whl#sha256=f296a3ba1267d43af1a7d96c9e57b83c5cf75366c604986a301c3a587d9b6751

===========================================

Loaded action execution configuration

AppConnector :Connector class File: app 

AppConnector :Asset config validated 

AppConnector :App config validated 

AppConnector :Current param: {}

AppConnector :__lock_info: {

    "enabled": true,

    "default_name": 73,

    "data_path": null,

    "timeout": 1200,

    "concurrency": true

}

AppConnector :lock_name 73

AppConnector :Version: UNSET_VERSION - set self.__version__ to emit here 

AppConnector :Git Hash: UNSET_GIT_HASH - set self.__git_hash__ to emit here 

AppConnector :Build Time:UNSET_BUILD_TIME - set self.__build_time__ to emit here 

AppConnector :action_id test_connectivity

Connecting to endpoint

AppConnector :AppConnector::handle_action exception occurred Exception: HTTPSConnectionPool(host='cplab.techservices.illinois.edu', port=443): Max retries exceeded with url: /api/oauth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f00390c8370>: Failed to establish a new connection: [Errno 110] Connection timed out'))

Traceback (most recent call last):

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn

    conn = connection.create_connection(

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection

    raise err

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection

    sock.connect(sa)

TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen

    httplib_response = self._make_request(

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 404, in _make_request

    self._validate_conn(conn)

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn

    conn.connect()

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect

    self.sock = conn = self._new_conn()

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn

    raise NewConnectionError(

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f00390c8370>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/requests/adapters.py", line 667, in send

    resp = conn.urlopen(

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 801, in urlopen

    retries = retries.increment(

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/urllib3/util/retry.py", line 594, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cplab.techservices.illinois.edu', port=443): Max retries exceeded with url: /api/oauth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f00390c8370>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/phantom/lib3/phantom/base_connector.py", line 3184, in _handle_action

    self.handle_action(curr_param)

  File "/opt/phantom/apps/testclearpass_AF98421B-D3B0-4A81-BF5C-FC227FCE0CB7/app.py", line 31, in handle_action

    self.nice_handle_action(param)

  File "/opt/phantom/apps/testclearpass_AF98421B-D3B0-4A81-BF5C-FC227FCE0CB7/dependencies/phtoolbox/app/base_connector.py", line 43, in nice_handle_action

    return self.actions[action_id](param)

  File "/opt/phantom/apps/testclearpass_AF98421B-D3B0-4A81-BF5C-FC227FCE0CB7/app.py", line 38, in _handle_test_connectivity

    self._clearpass_client._get_access_token()

  File "/opt/phantom/apps/testclearpass_AF98421B-D3B0-4A81-BF5C-FC227FCE0CB7/dependencies/clearpass/client.py", line 72, in _get_access_token

    res = requests.post(

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/requests/api.py", line 115, in post

    return request("post", url, data=data, json=json, **kwargs)

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/requests/api.py", line 59, in request

    return session.request(method=method, url=url, **kwargs)

  File "/opt/phantom/lib3/phantom/base_connector.py", line 328, in patched_session_request

    response = __original_session_request(self, method, url, **kwargs)

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/requests/sessions.py", line 589, in request

    resp = self.send(prep, **send_kwargs)

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/requests/sessions.py", line 703, in send

    r = adapter.send(request, **kwargs)

  File "/opt/phantom/usr/python39/lib/python3.9/site-packages/requests/adapters.py", line 700, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cplab.techservices.illinois.edu', port=443): Max retries exceeded with url: /api/oauth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f00390c8370>: Failed to establish a new connection: [Errno 110] Connection timed out'))

AppConnector :Action execution #1 () finished. Elapsed: 129.62511277198792 seconds 

AppConnector :All actions () finished. Elapsed: 129.625235080719 seconds 

AppConnector :Executed action  from app Test Clearpass. Elapsed: 129.62524127960205 seconds 

{"identifier": "test_connectivity", "result_data": [{"data": [], "extra_data": [], "summary": {}, "status": "failed", "message": "", "parameter": {}, "context": {}}, {"data": [], "extra_data": [], "summary": {}, "status": "failed", "message": "handle_action exception occurred. Error string: 'HTTPSConnectionPool(host='cplab.techservices.illinois.edu', port=443): Max retries exceeded with url: /api/oauth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f00390c8370>: Failed to establish a new connection: [Errno 110] Connection timed out'))'", "parameter": {}, "context": {}}], "result_summary": {"total_objects": 2, "total_objects_successful": 0}, "status": "failed", "message": "2 actions failed", "exception_occured": false, "action_cancelled": false}

Traceback (most recent call last):

  File "/opt/phantom/apps/testclearpass_AF98421B-D3B0-4A81-BF5C-FC227FCE0CB7/AF98421B-D3B0-4A81-BF5C-FC227FCE0CB7_2024_09_25_19_58_32.py", line 32, in <module>

    raise Exception("Action Failed")

Exception: Action Failed
```

**Comment by edthedev** [comment]
Per https://github.com/techservicesillinois/soar-clearpass/pull/22 the failure we were seeing appears to be due to SOAR not using the automation broker when `test_connectivity` is called in certain contexts.

**Comment by edthedev** [comment]
Removed `blocker` as we can add this later, if we prefer.

**Comment by edthedev** [comment]
I do still want us to make this change. I think we could simplify it though - since our error should be raised by `raise_on_status`, we know it will be a `HTTPError`. So this can be as simple as switching the `catch` to just `HTTPError` rather than `Exception`.

https://requests.readthedocs.io/en/latest/_modules/requests/models/#Response.raise_for_status

**Comment by edthedev** [comment]
When this change is complete, we should tag a new version of this library with a micro version update.

We can discuss, but 
I don't think we necessarily need to re-release both downstream projects for this change. It's probably fine for it to reach them in the course of other future updates.

**Comment by tzturner** [comment]
https://github.com/techservicesillinois/secops-soar-tdx/pull/161

We played around with Exceptions and tracebacks in the above PR and seem to have found a solution that we like.
